name: deep-storm3d
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.11.5
  - cloudpickle=0.5.3
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dask-core=0.18.2
  - dbus=1.13.6
  - decorator=4.3.0
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.3.0
  - intel-openmp=2018.0.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.0.3
  - mkl=2018.0.3
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - ncurses=6.1
  - networkx=2.1
  - ninja=1.8.2
  - numpy=1.14.3
  - numpy-base=1.14.3
  - olefile=0.45.1
  - openssl=1.1.1d
  - pcre=8.42
  - pillow=5.4.1
  - pip=9.0.1
  - pycparser=2.18
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.7.2
  - pytorch=1.3.1
  - pytz=2018.3
  - pywavelets=0.5.2
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.14.0
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - setuptools=39.0.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.26.0
  - tk=8.6.8
  - toolz=0.9.0
  - torchvision=0.4.2
  - tornado=5.0.1
  - wheel=0.30.0
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11

