name: deep-storm3d
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - cloudpickle=1.3.0
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.12.0
  - decorator=4.4.2
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - imageio=2.8.0
  - intel-openmp=2020.0
  - jpeg=9b
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - networkx=2.4
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.0.2u
  - pillow=5.4.1
  - pip=20.0.2
  - pycparser=2.20
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pywavelets=1.1.1
  - qt=5.9.6
  - scikit-image=0.16.2
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - setuptools=46.0.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.4.2
  - tornado=6.0.4
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

